name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DENO_DIR: $HOME/.deno

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Run tests
        run: deno test --coverage=coverage --allow-net --allow-env
        env:
          FILEBASE_TOKEN: ${{ secrets.FILEBASE_TOKEN }}
      - name: npm build
        run: deno run -A ./scripts/npm.ts
        env:
          FILEBASE_TOKEN: ${{ secrets.FILEBASE_TOKEN }}
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
