name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: npm build
        run: deno run -A ./scripts/npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}
        env:
          FILEBASE_TOKEN: ${{ secrets.FILEBASE_TOKEN }}
      - name: Publish to JSR
        if: startsWith(github.ref, 'refs/tags/')
        run: deno publish --set-version ${{steps.get_tag_version.outputs.TAG_VERSION}}
      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
